#pragma once


#ifdef PREVENT_FEATURE_MODIFICATION
	#error PREVENT_FEATURE_MODIFICATION
#endif


#ifndef MF_COROUTINE_STAGING_METHOD
	#define MF_COROUTINE_STAGING_METHOD GOTO_STATEMENT // <GOTO_STATEMENT / DUFFS_DEVICE>
#endif

#ifndef MF_DISABLE_CO_SLEEP
	#define MF_DISABLE_CO_SLEEP false
#endif

#ifndef MF_DISABLE_SUSPENSION_ON_FUTURE
	#define MF_DISABLE_SUSPENSION_ON_FUTURE false
#endif

#ifndef MF_DISABLE_IF_CONSTEXPR
	#define MF_DISABLE_IF_CONSTEXPR false
#endif

#ifndef MF_WAIT_FOR_ALL_TASKS
	#define MF_WAIT_FOR_ALL_TASKS true
#endif
